replicaCount: 1

team: jgerges

hostname: "jgerges"

imagePullSecrets: "docker-all"

dockerRegistry: "docker-all.nexus.murex.com"

requestsCap:
  enabled: false

cappedRequests:
  enabled: false 
  requests:
    cpu: 4000m
    memory: 4096Mi
  limits:
    cpu: 4000m
    memory: 4096Mi

nexus:
  image:
    name: "sonatype/nexus3"
    tag: "latest"
  port: 8081
  webcontext: nexus

ingress:
  enabled: true

service:
  enabled: true
  port: 8081

deployment:
  enabled: true
