replicaCount: 1

team: jgerges

hostname: "jgerges"

imagePullSecrets: "docker-all"

dockerRegistry: "docker-all.nexus.murex.com/"

app: fitnesse

cappedRequests:
  enabled: false
  requests:
    cpu: 500m
    memory: 1024Mi
  limits:
    cpu: 2000m
    memory: 2048Mi

fitnesse:
  image:
    name: "jgerges/fitnesse"
    tag: "latest"
  port: 9090
  webcontext: fitnesse

probes:
  enabled: true
  livenessProbe:
    initialDelaySeconds: 60
    periodsSeconds: 30
  readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 30
    failureThreshold: 6
    
ingress:
  enabled: true

service:
  enabled: true
  port: 9090
  type: LoadBalancer

deployment:
  enabled: true

persistance:
  enabled: true
  accessModes: ReadWriteMany
  storage: 5Gi
