replicaCount: 1

team: jgerges

hostname: "jgerges"

app: fitnesse

requests:
  cpu: 500m
  memory: 1024Mi

limits:
  cpu: 2000m
  memory: 2048Mi

fitnesse:
  image:
    name: "jgerges/fitnesse"
    tag: "latest"
  port: 9090
  webcontext: fitnesse

standalonejar:
  release: 20180127

ingress:
  enabled: true

service:
  enabled: true
  port: 9090

deployment:
  enabled: true
