{{- if .Values.deployment.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nexus
    team: {{ .Values.team }}
  name: {{ .Values.team }}-nexus-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nexus
      team: {{ .Values.team }}
  template:
    metadata:
      labels:
        app: nexus
        team: {{ .Values.team }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      containers:
        - name: nexus
          image: {{ .Values.dockerRegistry }}/{{ .Values.nexus.image.name }}:{{ .Values.nexus.image.tag }}
          ports:
          - containerPort: {{ .Values.nexus.port }}
            protocol: TCP
          {{- if .Values.cappedRequests.enabled }}
          resources:
            requests:
              cpu: {{ .Values.cappedRequests.requests.cpu }}
              memory: {{ .Values.cappedRequests.requests.memory }}
            limits:
              cpu: {{ .Values.cappedRequests.limits.cpu }}
              memory: {{ .Values.cappedRequests.limits.memory }}
          {{- end }}
          {{- if .Values.probes.enabled }}
          livenessProbe:
            httpGet:
              path: /{{ .Values.nexus.webcontext }}
              port: {{ .Values.nexus.port }}
            initialDelaySeconds: {{ .Values.probes.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /{{ .Values.nexus.webcontext }}
              port: {{ .Values.nexus.port }}
            initialDelaySeconds: {{ .Values.probes.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.probes.readinessProbe.failureThreshold }}
          {{- end }}
          env:
          - name: NEXUS_CONTEXT
            value: {{ .Values.nexus.webcontext }}
          volumeMounts:
          - mountPath: /nexus-data
            name: nexus-data
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: {{ .Values.team }}-nexus-pvc
{{- end }}
                                           
