apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nexus
    team: {{ .Values.team }}
  name: {{ .Values.team }}-nexus-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
