{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nexus
    team: {{ .Values.team }}
  name: {{ .Values.team }}-nexus-service
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.nexus.port }}
      name: nexusport
  selector:
    app: nexus
    team: {{ .Values.team }}
  type: LoadBalancer
{{- end }}
