- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: waiting for the service to be up
      uri:
        url: http://jgerges/sonar/setup
        status_code: 200
      register: result
      until: result.status == 200
      retries: 5
      delay: 30
      
    - name: upgrading database
      uri:
        url: http://jgerges/sonar/api/system/migrate_db
        method: POST
      
      

