- hosts: 127.0.0.1
  connection: local
  vars:
    team: "{{ team }}"

  tasks:
  - name: removing ingress rule to stop access to SonarQube
    helm:
        state: present
        name: sonarqube
        chart: 
            name: sonarqube
            source:
                type: directory
                location: ../
        values:
            ingress:
                enabled: false

 # - name: created backups later

  - name: scaling down the service for restart
    helm:
        state: present
        name: sonarqube
        chart: 
            name: sonarqube
            source:
                type: directory
                location: ../
        values:
            replicaCount: 0

    - name: scaling back up and enabling ingress
      helm:
        state: present
        name: sonarqube
        chart: 
            name: sonarqube
            source:
                type: directory
                location: ../
        values:
            replicaCount: 1
            ingress:
                enabled: true
            sonarqube:
                image:
                    tag: 8.4.1-community

    - name: waiting for the service to be up
      uri:
        url: http://istestkubmaster1.fr.murex.com/sonar/setup
        status_code: 200
      register: result
      until: result.status == 200
      retries: 5
      delay: 30
      
    - name: upgrading database
      uri:
        url: http://istestkubmaster1/sonar/api/system/migrate_db
        method: POST
      
      

