{{- if .Values.deployment.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app }}
    team: {{ .Values.team }}
  name: {{ .Values.team }}-{{ .Values.app }}-deployment
spec:
  imagePullSecrets: 
  - name: {{ .Values.imagePullSecrets }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
      team: {{ .Values.team }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
        team: {{ .Values.team }}
    spec:
      containers:
        - name: fitnesse
          image: {{ .Values.dockerRegistry }}/{{ .Values.fitnesse.image.name }}:{{ .Values.fitnesse.image.tag }}
          ports:
          - containerPort: {{ .Values.fitnesse.port }}
          volumeMounts:
          - mountPath: /opt/fitnesse/FitNesseRoot
            name: fitnesse-data
      volumes:
      - name: fitnesse-data
        persistentVolumeClaim:
          claimName: {{ .Values.team }}-{{ .Values.app }}-pvc
{{- end }}
