apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: fitnesse
    team: {{ .Values.team }}
  name: {{ .Values.team }}-fitnesse-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
