{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fitnesse
    team: {{ .Values.team }}
  name: {{ .Values.team }}-fitnesse-service
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.fitnesse.port }}
      name: fitnesseport
  selector:
    app: fitnesse
    team: {{ .Values.team }}
  type: LoadBalancer
{{- end }}
