{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app }}
    team: {{ .Values.team }}
  name: {{ .Values.team }}-{{ .Values.app }}-service
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.fitnesse.port }}
      name: fitnesseport
  selector:
    app: {{ .Values.app }}
    team: {{ .Values.team }}
  type: {{ .Values.service.type }}
{{- end }}
