{{- if .Values.deployment.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sonarqube
    team: {{ .Values.team }}
  name: {{ .Values.team }}-sonarqube-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  strategy: Recreate
  selector:
    matchLabels:
      app: sonarqube
      team: {{ .Values.team }}
  template:
    metadata:
      labels:
        app: sonarqube
        team: {{ .Values.team }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      terminationGracePeriodSeconds: 15
      initContainers:
      - name: sysctl
        image: {{ .Values.dockerRegistry }}busybox
        command: ['sysctl', '-w', 'vm.max_map_count=262144']
        securityContext:
          privileged: true
      {{- if .Values.persistance.enabled }}
      - name: fix-the-volume-permission
        image: {{ .Values.dockerRegistry }}busybox
        command:
        - sh
        - -c
        - chmod -R 777 /var/lib/postgresql /var/lib/postgresql/data /opt/sonarqube/extensions /opt/sonarqube/conf /opt/sonarqube/logs /opt/sonarqube/data && chown -R 999:999 /opt/sonarqube/data /opt/sonarqube/extensions /opt/sonarqube/logs /opt/sonarqube/conf
        securityContext:
          privileged: true
        volumeMounts:
        - name: sonar-extensions
          mountPath: /opt/sonarqube/extensions
        - name: sonar-data
          mountPath: /opt/sonarqube/data
        - name: sonar-conf
          mountPath: /opt/sonarqube/conf
        - name: sonar-logs
          mountPath: /opt/sonarqube/logs
        - name: postgresql
          mountPath: /var/lib/postgresql
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
      {{- if .Values.disablePlugins }}
      {{- range .Values.regex }}
      {{- if regexMatch .version $.Values.sonarqube.image.tag }}
      - name: removing-unsupported-plugins
        image: {{ $.Values.dockerRegistry }}busybox
        command:
        - sh
        - -c
        - rm -rf $(find /opt/sonarqube/extensions/plugins -regex '{{ .pattern }}' )
        volumeMounts:
        - name: sonar-extensions
          mountPath: /opt/sonarqube/extensions 
      {{- end }}
      {{- end }}
      {{- end }}
      {{- end }}
      containers:
        - name: sonardb
          image: {{ .Values.dockerRegistry }}{{ .Values.db.image.name }}:{{ .Values.db.image.tag }}
          ports:
          - containerPort: {{ .Values.db.port }}
          env:
          - name: DB_NAME
            value: {{ .Values.db.name }}
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.db.credentials.secret }}
                key: {{ .Values.db.credentials.usernameKey }}
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.db.credentials.secret }}
                key: {{ .Values.db.credentials.passwordKey }}
          {{- if .Values.persistance.enabled }}
          volumeMounts:
          - mountPath: /var/lib/postgresql
            name: postgresql
          - mountPath: /var/lib/postgresql/data
            name: postgresql-data
          {{- end }}
        - name: sonarqube
          image: {{ .Values.dockerRegistry }}{{ .Values.sonarqube.image.name }}:{{ .Values.sonarqube.image.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- if .Values.cappedRequests.enabled }}
          resources:
            requests:
              cpu: {{ .Values.cappedRequests.requests.cpu }}
              memory: {{ .Values.cappedRequests.requests.memory }}
            limits:
              cpu: {{ .Values.cappedRequests.limits.cpu }}
              memory: {{ .Values.cappedRequests.limits.memory }}
          {{- end }}
          {{- if .Values.probes.enabled }}
          livenessProbe:
            httpGet:
              path: /{{ .Values.sonarqube.webcontext }}
              port: {{ .Values.sonarqube.port }}
            initialDelaySeconds: {{ .Values.probes.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /{{ .Values.sonarqube.webcontext }}
              port: {{ .Values.sonarqube.port }}
            initialDelaySeconds: {{ .Values.probes.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.probes.readinessProbe.failureThreshold }}
          {{- end }}
          env:
          - name: SONARQUBE_JDBC_URL
            value: jdbc:postgresql://localhost:{{ .Values.db.port }}/{{ .Values.db.name }}
          - name: SONARQUBE_JDBC_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.db.credentials.secret }}
                key: {{ .Values.db.credentials.usernameKey }} 
          - name: SONARQUBE_JDBC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.db.credentials.secret }}
                key: {{ .Values.db.credentials.passwordKey }}
          - name: sonar.web.context
            value: /{{ .Values.sonarqube.webcontext }}
          {{- if .Values.sonarqube.proxy.enabled }}
          - name: http.proxyHost
            value: {{ .Values.sonarqube.http.proxyHort }}
          - name: http.proxyPort
            value: {{ .Values.sonarqube.http.proxyPort | quote }} 
          - name: https.proxyPort
            value: {{ .Values.sonarqube.https.proxyHost }}
          - name: https.proxyPort
            value: {{ .Values.sonarqube.https.proxyPort | quote }}
          {{- end }}
          {{- range .Values.env }}
          - name: {{ .name }}
            value: {{ .value | quote}}
          {{- end }}
          ports:
          - containerPort: {{ .Values.sonarqube.port }}
            protocol: TCP
      {{- if .Values.persistance.enabled }}
          volumeMounts:
          - mountPath: /opt/sonarqube/data/
            name: sonar-data
          - mountPath: /opt/sonarqube/extensions/
            name: sonar-extensions
          - mountPath: /opt/sonarqube/logs/
            name: sonar-logs
          - mountPath: /opt/sonarqube/conf/
            name: sonar-conf
      volumes:
      - name: sonar-data
        persistentVolumeClaim:
          claimName: {{ .Values.team }}-sq-{{ .Values.pvc.sqDataName }}-pvc 
      - name: sonar-extensions
        persistentVolumeClaim:
          claimName: {{ .Values.team }}-sq-{{ .Values.pvc.sqExtensionsName }}-pvc 
      - name: sonar-conf
        persistentVolumeClaim:
          claimName: {{ .Values.team }}-sq-{{ .Values.pvc.sqConfName }}-pvc 
      - name: sonar-logs
        persistentVolumeClaim:
          claimName: {{ .Values.team }}-sq-{{ .Values.pvc.sqLogsName }}-pvc 
      - name: postgresql
        persistentVolumeClaim:
          claimName: {{ .Values.team }}-sq-pg-{{ .Values.pvc.pgName }}-pvc 
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: {{ .Values.team }}-sq-pg-{{ .Values.pvc.pgDataName }}-pvc 
      {{- end }}
{{- end }}
