{{- if .Values.pvc.enabled -}}
{{- if .Values.persistance.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.team }}-sonarqube-postgresql-pvc
  labels:
    app: sonarqube
    team: {{ .Values.team }}
spec:
  accessModes:
    - {{ .Values.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistance.dbStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    labels:
      app: sonarqube
      team: {{ .Values.team }}
    name: {{ .Values.team }}-sonarqube-postgresql-data-pvc
spec:
    accessModes:
      - {{ .Values.pvc.accessMode }}
    resources:
      requests:
        storage: {{ .Values.persistance.dbDataStorage }}
{{- end }}
{{- end }}
