apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.team }}-sonarqube-postgresql-pvc
  labels:
    app: sonarqube
    team: {{ .Values.team }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    labels:
      app: sonarqube
      team: {{ .Values.team }}
    name: {{ .Values.team }}-sonarqube-postgresql-data-pvc
spec:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 2Gi
