{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sonarqube
    team: {{ .Values.team }}
  name: {{ .Values.team }}-sonarqube-service
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.sonarqube.port }}
      name: sonarport
  selector:
    app: sonarqube
    team: {{ .Values.team }}
  type: NodePort
{{- end }}
