{{- if .Values.pvc.enabled -}}
{{- if .Values.persistance.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: sonarqube
    team: {{ .Values.team }}
  name: sq-{{ .Values.pvc.sqDataName }}-pvc 
spec:
  accessModes:
    - {{ .Values.persistance.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistance.sqDataStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    labels:
      app: sonarqube
      team: {{ .Values.team }}
    name: sq-{{ .Values.pvc.sqExtensionsName }}-pvc 
spec:
  accessModes:
    - {{ .Values.persistance.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistance.sqExtensionsStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: sonarqube
    team: {{ .Values.team }}
  name: sq-{{ .Values.pvc.sqLogsName }}-pvc 
spec:
  accessModes:
    - {{ .Values.persistance.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistance.sqLogsStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: sonarqube
    team: {{ .Values.team }}
  name: sq-{{ .Values.pvc.sqConfName }}-pvc
spec:
  accessModes:
    - {{ .Values.persistance.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistance.sqConfStorage }}
{{- end }}    
{{- end }}
