{{- if .Values.pvc.enabled -}}
{{- if .Values.persistance.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: sonarqube
    team: {{ .Values.team }}
  name: {{ .Values.team }}-sq-{{ .Values.pvc.sqDataName }}-pvc #sonarqube-data-pvc
spec:
  accessModes:
    - {{ .Values.persistance.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistance.sqDataStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    labels:
      app: sonarqube
      team: {{ .Values.team }}
    name: {{ .Values.team }}-sq-{{ .Values.pvc.sqExtensionsName }}-pvc #sonarqube-extensions-pvc
spec:
  accessModes:
    - {{ .Values.persistance.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistance.sqExtensionsStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: sonarqube
    team: {{ .Values.team }}
  name: {{ .Values.team }}-sq-{{ .Values.pvc.sqLogsName }}-pvc #sonarqube-logs-pvc
spec:
  accessModes:
    - {{ .Values.persistance.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistance.sqLogsStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: sonarqube
    team: {{ .Values.team }}
  name: {{ .Values.team }}-sq-{{ .Values.sqConfName }}-pvc #sonarqube-conf-pvc
spec:
  accessModes:
    - {{ .Values.persistance.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistance.sqConfStorage }}
{{- end }}    
{{- end }}
