apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: sonarqube
    team: {{ .Values.team }}
  name: {{ .Values.team }}-sonarqube-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    labels:
      app: sonarqube
      team: {{ .Values.team }}
    name: {{ .Values.team }}-sonarqube-extensions-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: sonarqube
    team: {{ .Values.team }}
  name: {{ .Values.team }}-sonarqube-logs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: sonarqube
    team: {{ .Values.team }}
  name: {{ .Values.team }}-sonarqube-conf-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
    
